const observer = new IntersectionObserver(
  (entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    });
  },
  {
    threshold: 0.18,
  }
);

document.querySelectorAll('.reveal').forEach((el) => observer.observe(el));

const translations = {
  pt: {
    common: {
      logo_aria: 'CR Welding',
      logo_alt: 'Logo oficial CR Welding',
      nav_home: 'Início',
      nav_about: 'Empresa',
      nav_services: 'Serviços',
      nav_projects: 'Projetos',
      nav_faq: 'FAQ',
      nav_contact: 'Contato',
      nav_numbers: 'Números e Escala',
      nav_sectors: 'Setores Atendidos',
      nav_compliance: 'Certificações e Compliance',
      nav_sustainability_page: 'Sustentabilidade',
      nav_quality: 'Qualidade',
      nav_careers: 'Carreiras',
      footer_line1: 'CR Welding • Industrial Technology',
      footer_line2: 'Excelência, inovação e confiança para operações globais.',
      footer_nav_title: 'Navegação',
      footer_more_title: 'Institucional',
      footer_contact_title: 'Contato Comercial',
      media_img1_alt: 'Soldador executando solda de precisão em tubagem',
      media_img1_caption: 'Operação de soldagem especializada',
      media_img2_alt: 'Sistema de tubagem industrial complexa',
      media_img2_caption: 'Engenharia de tubagem e processo',
      media_img3_alt: 'Engenheira em inspeção técnica de equipamento industrial',
      media_img3_caption: 'Tecnologia e controle de execução',
    },
    pages: {
      home: {
        meta_title: 'CR Welding | Industrial Technology',
        meta_description: 'CR Welding: excelência em soldadura e manutenção industrial para operações globais.',
        hero_kicker: 'INDUSTRIAL TECHNOLOGY',
        hero_title: 'Estrutura industrial confiável para operações multinacionais.',
        hero_desc: 'A CR Welding entrega soldadura, manutenção industrial, montagem de tubagem, estruturas metálicas e skids com padrão técnico elevado, governança de execução e visão de longo prazo.',
        hero_btn_services: 'Explorar Serviços',
        hero_btn_projects: 'Ver Projetos',
        metric1_title: 'Soldadura de alta performance',
        metric1_desc: 'TIG, MIG/MAG e eletrodo para aplicações críticas',
        metric2_title: 'Execução industrial integrada',
        metric2_desc: 'Tubagem, estruturas e fabricação modular',
        metric3_title: 'Modelo corporativo confiável',
        metric3_desc: 'Qualidade, segurança e compromisso de longo prazo',
        hero_image_alt: 'Equipe em operação de soldagem industrial',
        home_overview_eyebrow: 'PRESENÇA GLOBAL',
        home_overview_title: 'Um parceiro industrial completo para a sua operação.',
        home_overview_desc: 'A CR Welding reúne expertise, qualidade e confiabilidade para entregar soluções sob medida, alinhadas às suas demandas e aos mais altos padrões de eficiência.',
        home_overview_card1_title: 'Sobre a Empresa',
        home_overview_card1_desc: 'Nossa história, cultura operacional e a visão que orienta cada entrega.',
        home_overview_card1_link: 'Saiba mais',
        home_overview_card2_title: 'Serviços e Capacidades',
        home_overview_card2_desc: 'Portfólio técnico, frentes de atuação e o processo que sustenta cada entrega.',
        home_overview_card2_link: 'Saiba mais',
        home_overview_card3_title: 'Projetos e FAQ',
        home_overview_card3_desc: 'Escopos já executados e respostas diretas para apoiar a sua decisão.',
        home_overview_card3_link: 'Saiba mais',
        home_diff_eyebrow: 'DIFERENCIAIS',
        home_diff_title: 'Estrutura técnica alinhada com grandes operações industriais.',
        home_diff1_title: 'Governança de execução',
        home_diff1_desc: 'Processos padronizados, previsibilidade de entrega e disciplina operacional.',
        home_diff2_title: 'Tecnologia aplicada',
        home_diff2_desc: 'Uso de abordagem moderna para produtividade, precisão e performance de campo.',
        home_diff3_title: 'Solidez reconhecida',
        home_diff3_desc: 'Confiabilidade reconhecida por compradores, parceiros e mercados internacionais.',
        home_diff4_title: 'Relacionamento de longo prazo',
        home_diff4_desc: 'Foco em confiança, continuidade contratual e geração de valor duradouro.',
        home_media_eyebrow: 'EM CAMPO',
        home_media_title: 'Precisão e padrão técnico em cada frente de trabalho.',
        home_cta_title: 'Conheça tudo o que a CR Welding pode fazer pela sua operação.',
        home_cta_desc: 'Explore nossas soluções e veja como a CR Welding apoia a sua operação com excelência técnica e confiança de longo prazo.',
        home_cta_btn_about: 'Conhecer a Empresa',
        home_cta_btn_contact: 'Abrir Contato',
        home_cert_eyebrow: 'PADRÕES E CONFORMIDADE',
        home_cert_title: 'Referências normativas que orientam a operação.',
        home_cert_quality: 'Qualidade',
        home_cert_env: 'Ambiente',
        home_cert_safety: 'Segurança',
        home_cert_steel: 'Estruturas',
        home_cert_weld: 'Soldadura',
      },
      about: {
        meta_title: 'CR Welding | Empresa',
        meta_description: 'Conheça a CR Welding, sua cultura operacional, manifesto e visão multinacional.',
        about_hero_eyebrow: 'EMPRESA',
        about_hero_title: 'Uma empresa industrial construída para confiança, escala e permanência.',
        about_hero_desc: 'A CR Welding combina excelência técnica, disciplina operacional e posicionamento corporativo para atuar como parceira relevante em cadeias industriais exigentes.',
        about_story_eyebrow: 'QUEM SOMOS',
        about_story_title: 'Origem, posicionamento e visão de crescimento.',
        about_story_p1: 'A CR Welding nasce com a proposta de elevar o padrão de soldadura e manutenção industrial por meio de uma execução disciplinada, tecnológica e orientada a relacionamento de longo prazo.',
        about_story_p2: 'Atuamos com autoridade técnica, modernidade e confiabilidade — atributos indispensáveis para acompanhar grandes clientes e operações multinacionais.',
        about_story_p3: 'Mais do que entregar serviços, a empresa estrutura soluções, organiza frentes industriais complexas e sustenta sua proposta de valor em excelência contínua, transparência e compromisso com resultados duradouros.',
        about_story_p4: 'O resultado é uma parceira preparada para contratos corporativos, projetos de grande porte e atuação sólida em diferentes geografias.',
        about_values_eyebrow: 'PRINCÍPIOS',
        about_values_title: 'Valores que sustentam a operação.',
        about_value1_title: 'Excelência',
        about_value1_desc: 'Busca permanente por qualidade técnica, acabamento e previsibilidade de entrega.',
        about_value2_title: 'Inovação',
        about_value2_desc: 'Adoção de abordagens modernas para ampliar precisão, produtividade e eficiência.',
        about_value3_title: 'Segurança',
        about_value3_desc: 'Disciplina operacional para proteger equipes, ativos, cronogramas e reputação.',
        about_value4_title: 'Confiança',
        about_value4_desc: 'Relações transparentes e duradouras com clientes, parceiros e fornecedores.',
        about_model_eyebrow: 'MODELO CORPORATIVO',
        about_model_title: 'Preparada para operações de maior porte.',
        about_stat1_value: 'Execução técnica',
        about_stat1_desc: 'Escopos industriais com controle operacional e foco em performance.',
        about_stat2_value: 'Proximidade institucional',
        about_stat2_desc: 'Diálogo próximo com compradores, áreas técnicas e parceiros globais.',
        about_stat3_value: 'Visão de longo prazo',
        about_stat3_desc: 'Crescimento sustentável e posicionamento consistente em mercados exigentes.',
        about_manifest_title: 'Manifesto institucional',
        about_manifest_p1: 'A CR Welding se posiciona como criadora de soluções e governante do próprio futuro. Sua proposta é construir um legado industrial baseado em tecnologia, precisão e responsabilidade.',
        about_manifest_p2: 'Essa visão faz da CR Welding uma parceira confiável para contratos de maior complexidade, relações de longo prazo e expansão internacional.',
        about_gallery_eyebrow: 'OPERAÇÃO',
        about_gallery_title: 'A engenharia da CR Welding em campo.',
        about_gallery_cap1: 'Soldagem especializada',
        about_gallery_cap2: 'Montagem de estruturas',
      },
      services: {
        meta_title: 'CR Welding | Serviços',
        meta_description: 'Conheça os serviços industriais da CR Welding, suas frentes técnicas e modelo de execução.',
        services_hero_eyebrow: 'SERVIÇOS',
        services_hero_title: 'Portfólio técnico estruturado para demandas industriais críticas.',
        services_hero_desc: 'A CR Welding organiza suas frentes de atuação para atender obras, manutenções, expansões de capacidade e necessidades recorrentes de suporte industrial.',
        services_matrix_eyebrow: 'CAPACIDADES',
        services_matrix_title: 'Frentes principais de entrega.',
        services_card1_title: 'Soldadura TIG',
        services_card1_desc: 'Aplicações que exigem alto controle de processo, acabamento e confiabilidade.',
        services_card2_title: 'Soldadura MIG/MAG',
        services_card2_desc: 'Execução eficiente para demandas industriais com produtividade e padronização.',
        services_card3_title: 'Soldadura por eletrodo',
        services_card3_desc: 'Versatilidade para diferentes ambientes, estruturas e frentes de manutenção.',
        services_card4_title: 'Montagem de tubagem',
        services_card4_desc: 'Instalação e organização de sistemas industriais com rigor dimensional e segurança.',
        services_card5_title: 'Estruturas metálicas',
        services_card5_desc: 'Construção, reforço e suporte estrutural para unidades produtivas e utilidades.',
        services_card6_title: 'Fabricação de skids',
        services_card6_desc: 'Soluções modulares robustas para integração operacional e ganho de eficiência.',
        services_process_eyebrow: 'MODELO DE EXECUÇÃO',
        services_process_title: 'Como estruturamos cada projeto.',
        services_step1_title: 'Diagnóstico',
        services_step1_desc: 'Levantamento técnico, alinhamento de escopo e definição de prioridades.',
        services_step2_title: 'Planejamento',
        services_step2_desc: 'Organização de recursos, cronograma, segurança e sequência de execução.',
        services_step3_title: 'Entrega',
        services_step3_desc: 'Execução com disciplina operacional, controle de qualidade e comunicação clara.',
        services_step4_title: 'Continuidade',
        services_step4_desc: 'Suporte para novas etapas, recorrência contratual e evolução da operação.',
        services_sectors_eyebrow: 'SETORES',
        services_sectors_title: 'Ambientes onde a CR Welding atua.',
        services_sector1_title: 'Plantas industriais',
        services_sector1_desc: 'Operações fabris com demandas de manutenção, expansão e confiabilidade.',
        services_sector2_title: 'Utilidades e infraestrutura',
        services_sector2_desc: 'Sistemas de suporte à produção com necessidade de performance estável.',
        services_sector3_title: 'Projetos especiais',
        services_sector3_desc: 'Escopos sob medida que exigem flexibilidade técnica e visão de engenharia.',
        services_sector4_title: 'Parcerias recorrentes',
        services_sector4_desc: 'Modelos contratuais de relacionamento contínuo e resposta operacional rápida.',
        services_cta_title: 'Leve a próxima demanda industrial para uma estrutura preparada.',
        services_cta_desc: 'Fale com a nossa equipe para alinhar escopo, prioridade e os próximos passos da sua demanda.',
        services_cta_btn_contact: 'Solicitar contato',
        services_cta_btn_projects: 'Ver entregas',
      },
      projects: {
        meta_title: 'CR Welding | Projetos',
        meta_description: 'Veja os tipos de projetos e entregas representativas da CR Welding para operações industriais.',
        projects_hero_eyebrow: 'PROJETOS',
        projects_hero_title: 'Escopos representativos que demonstram capacidade de entrega.',
        projects_hero_desc: 'Conheça os tipos de serviço já executados pela CR Welding e a capacidade técnica por trás de cada entrega.',
        projects_grid_eyebrow: 'ENTREGAS',
        projects_grid_title: 'Categorias de projetos executados.',
        projects_card1_title: 'Montagem de tubagem industrial',
        projects_card1_desc: 'Execução de linhas e interligações com rigor dimensional, segurança e continuidade operacional.',
        projects_card2_title: 'Estruturas metálicas de suporte',
        projects_card2_desc: 'Fabricação e montagem de componentes estruturais para áreas produtivas e utilidades.',
        projects_card3_title: 'Skids e soluções modulares',
        projects_card3_desc: 'Desenvolvimento de conjuntos robustos para integração mais ágil em plantas industriais.',
        projects_card4_title: 'Intervenções de manutenção',
        projects_card4_desc: 'Atuação em melhorias, correções e reforços com foco em disponibilidade e confiabilidade.',
        projects_method_eyebrow: 'ABORDAGEM',
        projects_method_title: 'Como conduzimos cada entrega.',
        projects_stat1_value: 'Escopo',
        projects_stat1_desc: 'Cada entrega é organizada por frente de serviço e resultado operacional esperado.',
        projects_stat2_value: 'Evidência',
        projects_stat2_desc: 'Registros de campo e detalhamento técnico que comprovam a qualidade de cada execução.',
        projects_stat3_value: 'Confidencialidade',
        projects_stat3_desc: 'Casos identificados por cliente são compartilhados de forma reservada, mediante autorização comercial.',
        projects_media_eyebrow: 'EM CAMPO',
        projects_media_title: 'Registros que mostram capacidade e padronização.',
        projects_media_caption1: 'Execução técnica e ambiente de campo.',
        projects_media_caption2: 'Padrão técnico consistente em cada frente.',
        projects_media_caption3: 'Organização e disciplina operacional em campo.',
        projects_cta_title: 'Conheça em detalhe a capacidade de entrega da CR Welding.',
        projects_cta_desc: 'Fale com a equipe para conhecer casos reais, indicadores de resultado e referências autorizadas.',
        projects_cta_btn_contact: 'Solicitar reunião',
        projects_cta_btn_faq: 'Ler FAQ',
      },
      faq: {
        meta_title: 'CR Welding | FAQ',
        meta_description: 'Perguntas frequentes sobre atuação, escopo, prazos e relacionamento comercial da CR Welding.',
        faq_hero_eyebrow: 'FAQ',
        faq_hero_title: 'Respostas objetivas para decisões comerciais mais rápidas.',
        faq_hero_desc: 'Reunimos aqui as dúvidas mais comuns sobre escopo, capacidade, formato de contratação e início de relacionamento com a CR Welding.',
        faq_list_eyebrow: 'PERGUNTAS FREQUENTES',
        faq_list_title: 'O que compradores e parceiros costumam perguntar.',
        faq_q1: 'Quais serviços a CR Welding executa?',
        faq_a1: 'A empresa atua com soldadura TIG, MIG/MAG e eletrodo, montagem de tubagem, estruturas metálicas, fabricação de skids e suporte técnico industrial.',
        faq_q2: 'A empresa atende demandas recorrentes ou apenas projetos pontuais?',
        faq_a2: 'Os dois formatos são possíveis. A operação pode atender intervenções pontuais, projetos sob demanda e relacionamentos recorrentes conforme necessidade do cliente.',
        faq_q3: 'A CR Welding está preparada para clientes de maior porte?',
        faq_a3: 'Sim. O posicionamento institucional, a disciplina operacional e a organização das frentes técnicas foram estruturados para dialogar com operações mais exigentes e contratos de maior responsabilidade.',
        faq_q4: 'Como funciona o início de uma negociação?',
        faq_a4: 'Normalmente começa com um contato comercial, alinhamento inicial de escopo, entendimento de prioridade operacional e definição de próximos passos técnicos.',
        faq_q5: 'Há flexibilidade para projetos sob medida?',
        faq_a5: 'Sim. A empresa se posiciona como criadora de soluções, o que inclui adaptação de frentes, recursos e estrutura de entrega ao contexto do projeto.',
        faq_q6: 'Posso ver casos reais e referências de clientes?',
        faq_a6: 'Sim. Compartilhamos categorias de escopos já executados e, mediante autorização comercial, apresentamos casos identificados por cliente de forma reservada.',
        faq_q7: 'A CR Welding atende clientes e operações internacionais?',
        faq_a7: 'Sim. Atuamos com padrão técnico e comunicação bilíngue (português e inglês), preparados para operações e contratos em contexto multinacional.',
        faq_q8: 'Qual é o melhor próximo passo para iniciar uma conversa?',
        faq_a8: 'Usar a página de contato para solicitar reunião executiva ou enviar um resumo inicial da demanda operacional.',
        faq_cta_title: 'Se a sua dúvida for específica, leve a conversa para o contato comercial.',
        faq_cta_desc: 'A página de contato organiza o primeiro atendimento e permite direcionar a pauta com mais precisão.',
        faq_cta_btn_contact: 'Ir para contato',
        faq_cta_btn_services: 'Ver serviços',
      },
      contact: {
        meta_title: 'CR Welding | Contato',
        meta_description: 'Entre em contato com a CR Welding para apresentar seu escopo, marcar reunião e iniciar relacionamento comercial.',
        contact_hero_eyebrow: 'CONTATO',
        contact_hero_title: 'Abra a conversa comercial com clareza de escopo e prioridade.',
        contact_hero_desc: 'Aqui você inicia o primeiro contato institucional, marca uma reunião e envia um resumo da sua necessidade operacional.',
        contact_channels_eyebrow: 'CANAIS',
        contact_channels_title: 'Formas principais de iniciar a conversa.',
        contact_card1_title: 'E-mail comercial',
        contact_card1_desc: 'Ideal para envio de resumo inicial, escopo preliminar e documentação de apoio.',
        contact_card2_title: 'Reunião executiva',
        contact_card2_desc: 'Indicado para oportunidades maiores, alinhamento estratégico e relacionamento de longo prazo.',
        contact_card2_meta: 'Agendamento mediante contato inicial',
        contact_card3_title: 'Triagem de demanda',
        contact_card3_desc: 'Organiza urgência, frente técnica envolvida e próximos passos comerciais.',
        contact_card3_meta: 'Resposta conforme prioridade operacional',
        contact_form_eyebrow: 'FORMULÁRIO INICIAL',
        contact_form_title: 'Envie um briefing executivo.',
        contact_field_name: 'Nome',
        contact_field_company: 'Empresa',
        contact_field_email: 'E-mail',
        contact_field_scope: 'Frente de interesse',
        contact_field_message: 'Resumo da necessidade',
        contact_placeholder_name: 'Seu nome',
        contact_placeholder_company: 'Nome da empresa',
        contact_placeholder_email: 'voce@empresa.com',
        contact_placeholder_scope: 'Ex.: tubagem, estrutura, skid',
        contact_placeholder_message: 'Descreva o contexto, prioridade e objetivo do contato.',
        contact_form_button: 'Enviar briefing',
        contact_commitment_eyebrow: 'COMPROMISSOS',
        contact_commitment_title: 'Nosso compromisso com cada contato.',
        contact_commitment1_title: 'Clareza',
        contact_commitment1_desc: 'Leitura rápida da demanda e direcionamento inicial consistente.',
        contact_commitment2_title: 'Profissionalismo',
        contact_commitment2_desc: 'Atendimento profissional alinhado a operações de maior porte.',
        contact_commitment3_title: 'Continuidade',
        contact_commitment3_desc: 'Abertura de relacionamento comercial com visão de médio e longo prazo.',
      },
      'numbers-scale': {
        meta_title: 'CR Welding | Números e Escala',
        meta_description: 'Estrutura corporativa da CR Welding com foco em escala operacional, presença institucional e capacidade de crescimento.',
        numbers_hero_eyebrow: 'NÚMEROS E ESCALA',
        numbers_hero_title: 'Porte, maturidade e capacidade de crescimento para sustentar a sua operação.',
        numbers_hero_desc: 'A CR Welding está preparada para sustentar conversas com clientes maiores, procurement e parceiros estratégicos, com solidez operacional e institucional.',
        numbers_snapshot_eyebrow: 'VISÃO GERAL',
        numbers_snapshot_title: 'Indicadores institucionais centrais.',
        numbers_snapshot_desc: 'Indicadores oficiais são disponibilizados conforme a CR Welding valida os números para divulgação comercial.',
        numbers_card1_title: 'Ano de referência',
        numbers_card1_desc: 'Fundação, ciclo atual e marcos operacionais que situam a trajetória da empresa.',
        numbers_card1_value: 'Dado em consolidação',
        numbers_card2_title: 'Capacidade operacional',
        numbers_card2_desc: 'Equipe, mobilização, frentes simultâneas ou cobertura técnica.',
        numbers_card2_value: 'Dado em consolidação',
        numbers_card3_title: 'Mercados atendidos',
        numbers_card3_desc: 'Setores, regiões ou países conforme a maturidade comercial da empresa.',
        numbers_card3_value: 'Dado em consolidação',
        numbers_card4_title: 'Projetos entregues',
        numbers_card4_desc: 'Histórico de obras, manutenções e contratos executados ao longo da operação.',
        numbers_card4_value: 'Dado em consolidação',
        numbers_scale_eyebrow: 'ESCALA',
        numbers_scale_title: 'Porte que se mede por estrutura, disciplina e consistência.',
        numbers_scale_p1: 'Escala não se resume a faturamento. Ela se demonstra por estrutura, disciplina de execução, setores atendidos, capacidade de resposta e consistência operacional.',
        numbers_scale_p2: 'A CR Welding organiza sua operação para responder a contratos mais exigentes — e essa preparação é, por si só, um compromisso de confiança.',
        numbers_scale_p3: 'Os indicadores oficiais abrangem números de equipe, áreas de atuação, volume de entregas, presença geográfica e evolução de capacidade.',
        numbers_scale_p4: 'A CR Welding comunica maturidade corporativa com transparência, sem inventar indicadores ou comprometer a credibilidade da marca.',
        numbers_categories_eyebrow: 'CATEGORIAS',
        numbers_categories_title: 'Os números que mais importam para a sua decisão.',
        numbers_info1_title: 'Escala operacional',
        numbers_info1_desc: 'Equipe, frentes de trabalho, capacidade de mobilização e especialidades disponíveis.',
        numbers_info2_title: 'Escala comercial',
        numbers_info2_desc: 'Segmentos atendidos, mercados alcançados, contratos representativos e recorrência.',
        numbers_info3_title: 'Escala institucional',
        numbers_info3_desc: 'Certificações, processos, governança, qualidade e imagem de empresa preparada.',
        numbers_cta_title: 'Solidez operacional e institucional pronta para conversas de maior porte.',
        numbers_cta_desc: 'Fale com a equipe para receber indicadores, marcos de crescimento e referências autorizadas pela empresa.',
        numbers_cta_btn_contact: 'Avançar para contato',
        numbers_cta_btn_projects: 'Ver projetos',
      },
      sectors: {
        meta_title: 'CR Welding | Setores Atendidos',
        meta_description: 'Conheça os setores industriais que a CR Welding pode atender com soluções de soldadura, montagem e fabricação industrial.',
        sectors_hero_eyebrow: 'SETORES ATENDIDOS',
        sectors_hero_title: 'Onde a CR Welding gera valor para a sua operação industrial.',
        sectors_hero_desc: 'Atuamos em diferentes setores industriais com a mesma exigência técnica, adaptando capacidade e método ao contexto de cada operação.',
        sectors_grid_eyebrow: 'MERCADOS',
        sectors_grid_title: 'Setores industriais compatíveis com a proposta da empresa.',
        sector1_title: 'Metalomecânico',
        sector1_desc: 'Estruturas, suportes, componentes e demandas fabris com exigência técnica e operacional.',
        sector2_title: 'Energia e utilidades',
        sector2_desc: 'Sistemas de apoio, interligações, reforços e frentes críticas para continuidade operacional.',
        sector3_title: 'Químico e processo',
        sector3_desc: 'Ambientes que exigem disciplina de montagem, confiabilidade e leitura técnica cuidadosa.',
        sector4_title: 'Alimentar',
        sector4_desc: 'Estruturas, tubagem e suportes para operações que dependem de padrão e previsibilidade.',
        sector5_title: 'Manutenção industrial',
        sector5_desc: 'Intervenções corretivas, preventivas e melhorias com foco em disponibilidade de ativos.',
        sector6_title: 'Projetos especiais',
        sector6_desc: 'Demandas sob medida com necessidade de adaptação técnica e execução coordenada.',
        sectors_logic_eyebrow: 'ADERÊNCIA SETORIAL',
        sectors_logic_title: 'Por que a experiência setorial faz diferença na sua operação.',
        sectors_logic_p1: 'Grandes operações industriais não contratam apenas um serviço. Avaliam aderência setorial, familiaridade com o contexto operacional e capacidade de responder a exigências específicas — e é nisso que a CR Welding se diferencia.',
        sectors_logic_p2: 'Por isso, estruturamos nossa atuação por setor: para responder com precisão a operações complexas, sem soluções genéricas.',
        sectors_logic_p3: 'Cada setor pode ser aprofundado com cases, requisitos técnicos e certificações específicas, conforme a sua necessidade.',
        sectors_logic_p4: 'É essa abordagem que faz da CR Welding uma parceira industrial relevante, e não apenas mais um prestador de serviços.',
        sectors_cta_title: 'Cada setor se conecta a entregas, indicadores e compliance da CR Welding.',
        sectors_cta_desc: 'Fale com a equipe para conhecer a atuação da CR Welding no setor de interesse.',
        sectors_cta_btn_projects: 'Ver projetos',
        sectors_cta_btn_compliance: 'Ver compliance',
      },
      compliance: {
        meta_title: 'CR Welding | Certificações e Compliance',
        meta_description: 'Veja como a CR Welding pode apresentar certificações, qualidade, segurança, ambiente e governança operacional de forma institucional.',
        compliance_hero_eyebrow: 'CERTIFICAÇÕES E COMPLIANCE',
        compliance_hero_title: 'Confiança que começa antes mesmo da negociação avançar.',
        compliance_hero_desc: 'Empresas industriais fortes não falam apenas de serviço. Elas demonstram método, sistema, qualidade, segurança e confiabilidade documental — e é assim que a CR Welding se posiciona.',
        compliance_blocks_eyebrow: 'ESTRUTURA',
        compliance_blocks_title: 'Pilares que sustentam a credibilidade técnica da CR Welding.',
        compliance_card1_title: 'Qualidade',
        compliance_card1_desc: 'Procedimentos, inspeção, disciplina de execução e melhoria contínua.',
        compliance_card2_title: 'Segurança',
        compliance_card2_desc: 'Práticas de prevenção, conduta operacional e cultura de responsabilidade.',
        compliance_card3_title: 'Ambiente',
        compliance_card3_desc: 'Eficiência de recursos, organização e redução de impactos evitáveis.',
        compliance_card4_title: 'Governança',
        compliance_card4_desc: 'Rastreabilidade, clareza de escopo, documentação e consistência institucional.',
        compliance_matrix_eyebrow: 'MATRIZ DE CONFIANÇA',
        compliance_matrix_title: 'A base documental que sustenta cada compromisso.',
        compliance_stat1_title: 'Certificações formais',
        compliance_stat1_desc: 'Selos, escopo de certificação, vigência e referência documental de cada norma aplicável.',
        compliance_stat1_value: 'Disponível sob consulta comercial',
        compliance_stat2_title: 'Procedimentos internos',
        compliance_stat2_desc: 'Políticas de qualidade, segurança, ambiente e padrões de execução.',
        compliance_stat2_value: 'Disponível sob consulta comercial',
        compliance_stat3_title: 'Requisitos por cliente',
        compliance_stat3_desc: 'Aderência comprovada a exigências contratuais e operacionais de cada cliente.',
        compliance_stat3_value: 'Disponível sob consulta comercial',
        compliance_stat4_title: 'Evidência institucional',
        compliance_stat4_desc: 'Apresentação clara para auditorias, parceiros e áreas de procurement.',
        compliance_stat4_value: 'Disponível sob consulta comercial',
        compliance_why_eyebrow: 'POR QUE ISSO IMPORTA',
        compliance_why_title: 'Compliance reduz risco. E menos risco significa decisões mais seguras para você.',
        compliance_why_p1: 'Organização documental, processos claros e transparência sobre qualidade e segurança eliminam dúvidas antes mesmo da fase técnica detalhada.',
        compliance_why_p2: 'É o padrão dos fornecedores preparados para dialogar com operações de maior porte e cadeias industriais exigentes — e é assim que trabalhamos.',
        compliance_why_p3: 'A experiência do setor confirma: confiança se constrói com evidência e método, não apenas com discurso comercial.',
        compliance_why_p4: 'Por isso, tratamos o compliance como parte essencial de cada entrega — e não como formalidade.',
        compliance_cta_title: 'Método, procedimentos e evidências que dão peso a cada negociação.',
        compliance_cta_desc: 'A CR Welding garante maturidade, controle e transparência em cada etapa do relacionamento.',
        compliance_cta_btn_quality: 'Ver qualidade',
        compliance_cta_btn_contact: 'Ir para contato',
      },
      'sustainability-page': {
        meta_title: 'CR Welding | Sustentabilidade',
        meta_description: 'Conheça a visão de sustentabilidade da CR Welding e seus compromissos com eficiência, responsabilidade e legado positivo.',
        sustain_page_hero_eyebrow: 'SUSTENTABILIDADE',
        sustain_page_hero_title: 'Crescimento industrial com responsabilidade, eficiência e visão de legado.',
        sustain_page_hero_desc: 'A CR Welding trata sustentabilidade como disciplina operacional: menos desperdício, melhor uso de recursos e decisões que fortalecem o futuro da empresa, dos clientes e do entorno.',
        sustain_page_pillars_eyebrow: 'COMPROMISSOS',
        sustain_page_pillars_title: 'Pilares que orientam nossa atuação.',
        sustain_page_card1_title: 'Eficiência de recursos',
        sustain_page_card1_desc: 'Busca contínua por processos mais enxutos, menor retrabalho e melhor aproveitamento de materiais.',
        sustain_page_card2_title: 'Responsabilidade operacional',
        sustain_page_card2_desc: 'Organização de frentes com disciplina técnica, segurança e controle sobre impactos evitáveis.',
        sustain_page_card3_title: 'Parcerias conscientes',
        sustain_page_card3_desc: 'Relações com clientes e fornecedores baseadas em continuidade, transparência e evolução de práticas.',
        sustain_page_card4_title: 'Visão de longo prazo',
        sustain_page_card4_desc: 'Crescimento com consistência, reputação e legado institucional positivo.',
        sustain_page_actions_eyebrow: 'PRÁTICAS',
        sustain_page_actions_title: 'Como isso aparece na prática.',
        sustain_page_step1_title: 'Planejamento',
        sustain_page_step1_desc: 'Definição de escopo e sequência com foco em redução de desperdício e melhor uso de tempo e materiais.',
        sustain_page_step2_title: 'Execução',
        sustain_page_step2_desc: 'Padrão técnico orientado à qualidade para minimizar retrabalho e intervenções corretivas desnecessárias.',
        sustain_page_step3_title: 'Disciplina',
        sustain_page_step3_desc: 'Segurança, organização do ambiente e conduta operacional compatíveis com operações de maior porte.',
        sustain_page_step4_title: 'Evolução',
        sustain_page_step4_desc: 'Aprendizado contínuo para elevar performance, eficiência e maturidade da empresa.',
      },
      quality: {
        meta_title: 'CR Welding | Qualidade',
        meta_description: 'Conheça a visão de qualidade da CR Welding, seus princípios de execução e melhoria contínua.',
        quality_hero_eyebrow: 'QUALIDADE',
        quality_hero_title: 'Qualidade como disciplina de execução, reputação e permanência.',
        quality_hero_desc: 'Na CR Welding, qualidade não é acabamento isolado. É método, controle, previsibilidade e compromisso com resultados que sustentam confiança comercial.',
        quality_principles_eyebrow: 'PRINCÍPIOS',
        quality_principles_title: 'Elementos que formam nosso padrão interno.',
        quality_card1_title: 'Padronização',
        quality_card1_desc: 'Processos consistentes para reduzir variação e elevar a confiabilidade de cada entrega.',
        quality_card2_title: 'Controle',
        quality_card2_desc: 'Acompanhamento técnico e leitura clara do escopo durante toda a execução.',
        quality_card3_title: 'Rastreabilidade',
        quality_card3_desc: 'Organização das etapas e decisões para facilitar comunicação e evolução operacional.',
        quality_card4_title: 'Melhoria contínua',
        quality_card4_desc: 'Aprendizado incorporado ao método para aumentar performance e previsibilidade.',
        quality_model_eyebrow: 'MODELO',
        quality_model_title: 'Como a qualidade aparece nas frentes de serviço.',
        quality_model_p1: 'Na soldadura, qualidade significa controle de processo, coerência de execução e redução de retrabalho.',
        quality_model_p2: 'Na montagem e fabricação, significa precisão, leitura correta do escopo e alinhamento entre entrega técnica e necessidade do cliente.',
        quality_model_p3: 'No relacionamento comercial, qualidade também significa clareza, consistência de comunicação e compromisso com o que foi acordado.',
        quality_model_p4: 'Esse conjunto fortalece reputação, continuidade contratual e capacidade de atuar em operações mais exigentes.',
      },
      careers: {
        meta_title: 'CR Welding | Carreiras',
        meta_description: 'Conheça a página de carreiras da CR Welding, cultura de trabalho e perfil de profissionais buscados.',
        careers_hero_eyebrow: 'CARREIRAS',
        careers_hero_title: 'Pessoas que constroem padrão, confiança e continuidade operacional.',
        careers_hero_desc: 'Procuramos profissionais alinhados à disciplina industrial, ao padrão técnico e à ambição de crescer junto com a CR Welding.',
        careers_culture_eyebrow: 'CULTURA',
        careers_culture_title: 'O que valorizamos nas equipes.',
        careers_card1_title: 'Disciplina',
        careers_card1_desc: 'Compromisso com padrão técnico, segurança e organização no trabalho.',
        careers_card2_title: 'Aprendizado',
        careers_card2_desc: 'Evolução contínua como parte do crescimento individual e coletivo.',
        careers_card3_title: 'Responsabilidade',
        careers_card3_desc: 'Postura profissional compatível com operações e clientes de maior exigência.',
        careers_card4_title: 'Parceria',
        careers_card4_desc: 'Capacidade de colaborar, respeitar processos e fortalecer o time.',
        careers_profiles_eyebrow: 'PERFIS',
        careers_profiles_title: 'Perfis que fazem a diferença em nossas equipes.',
        careers_profile1_title: 'Soldadores especializados',
        careers_profile1_desc: 'Profissionais com foco em qualidade, método e consistência técnica.',
        careers_profile2_title: 'Montadores e apoio de campo',
        careers_profile2_desc: 'Perfis operacionais orientados à execução segura e organizada.',
        careers_profile3_title: 'Coordenação técnica',
        careers_profile3_desc: 'Lideranças com visão de processo, gente, entrega e relacionamento com cliente.',
        careers_cta_title: 'Faça parte do crescimento industrial da CR Welding.',
        careers_cta_desc: 'Envie sua apresentação e mostre como você se alinha à cultura, à ambição e ao padrão profissional da CR Welding.',
        careers_cta_btn_email: 'Enviar apresentação',
        careers_cta_btn_about: 'Conhecer a empresa',
      },
    },
  },
  en: {
    common: {
      logo_aria: 'CR Welding',
      logo_alt: 'CR Welding official logo',
      nav_home: 'Home',
      nav_about: 'Company',
      nav_services: 'Services',
      nav_projects: 'Projects',
      nav_faq: 'FAQ',
      nav_contact: 'Contact',
      nav_numbers: 'Numbers and Scale',
      nav_sectors: 'Served Sectors',
      nav_compliance: 'Certifications and Compliance',
      nav_sustainability_page: 'Sustainability',
      nav_quality: 'Quality',
      nav_careers: 'Careers',
      footer_line1: 'CR Welding • Industrial Technology',
      footer_line2: 'Excellence, innovation, and trust for global operations.',
      footer_nav_title: 'Navigation',
      footer_more_title: 'Institutional',
      footer_contact_title: 'Commercial Contact',
      media_img1_alt: 'Welder performing precision welding on piping',
      media_img1_caption: 'Specialized welding operation',
      media_img2_alt: 'Complex industrial piping system',
      media_img2_caption: 'Piping and process engineering',
      media_img3_alt: 'Engineer performing technical inspection of industrial equipment',
      media_img3_caption: 'Technology and execution control',
    },
    pages: {
      home: {
        meta_title: 'CR Welding | Industrial Technology',
        meta_description: 'CR Welding: excellence in welding and industrial maintenance for global operations.',
        hero_kicker: 'INDUSTRIAL TECHNOLOGY',
        hero_title: 'Reliable industrial structure for multinational operations.',
        hero_desc: 'CR Welding delivers welding, industrial maintenance, piping assembly, metal structures, and skids with high technical standards, execution governance, and a long-term vision.',
        hero_btn_services: 'Explore Services',
        hero_btn_projects: 'View Projects',
        metric1_title: 'High-performance welding',
        metric1_desc: 'TIG, MIG/MAG, and electrode for critical applications',
        metric2_title: 'Integrated industrial execution',
        metric2_desc: 'Piping, structures, and modular fabrication',
        metric3_title: 'Reliable corporate model',
        metric3_desc: 'Quality, safety, and long-term commitment',
        hero_image_alt: 'Team performing industrial welding operation',
        home_overview_eyebrow: 'GLOBAL PRESENCE',
        home_overview_title: 'A complete industrial partner for your operation.',
        home_overview_desc: 'CR Welding combines expertise, quality, and reliability to deliver tailored solutions aligned with your needs and the highest efficiency standards.',
        home_overview_card1_title: 'About the Company',
        home_overview_card1_desc: 'Our history, operational culture, and the vision that guides every delivery.',
        home_overview_card1_link: 'Learn more',
        home_overview_card2_title: 'Services and Capabilities',
        home_overview_card2_desc: 'Technical portfolio, delivery fronts, and the process behind every job.',
        home_overview_card2_link: 'Learn more',
        home_overview_card3_title: 'Projects and FAQ',
        home_overview_card3_desc: 'Scopes already executed and direct answers to support your decision.',
        home_overview_card3_link: 'Learn more',
        home_diff_eyebrow: 'DIFFERENTIALS',
        home_diff_title: 'Technical structure aligned with large industrial operations.',
        home_diff1_title: 'Execution governance',
        home_diff1_desc: 'Standardized processes, delivery predictability, and operational discipline.',
        home_diff2_title: 'Applied technology',
        home_diff2_desc: 'Modern approach to productivity, precision, and field performance.',
        home_diff3_title: 'Recognized solidity',
        home_diff3_desc: 'Reliability recognized by buyers, partners, and international markets.',
        home_diff4_title: 'Long-term relationships',
        home_diff4_desc: 'Focus on trust, contractual continuity, and lasting value generation.',
        home_media_eyebrow: 'IN THE FIELD',
        home_media_title: 'Precision and technical standard on every front.',
        home_cta_title: 'Discover everything CR Welding can do for your operation.',
        home_cta_desc: 'Explore our solutions and see how CR Welding supports your operation with technical excellence and long-term trust.',
        home_cta_btn_about: 'Learn About the Company',
        home_cta_btn_contact: 'Open Contact',
        home_cert_eyebrow: 'STANDARDS & COMPLIANCE',
        home_cert_title: 'Normative references that guide the operation.',
        home_cert_quality: 'Quality',
        home_cert_env: 'Environment',
        home_cert_safety: 'Safety',
        home_cert_steel: 'Structures',
        home_cert_weld: 'Welding',
      },
      about: {
        meta_title: 'CR Welding | Company',
        meta_description: 'Learn about CR Welding, its operational culture, manifesto, and multinational vision.',
        about_hero_eyebrow: 'COMPANY',
        about_hero_title: 'An industrial company built for trust, scale, and permanence.',
        about_hero_desc: 'CR Welding combines technical excellence, operational discipline, and corporate positioning to act as a relevant partner in demanding industrial chains.',
        about_story_eyebrow: 'WHO WE ARE',
        about_story_title: 'Origin, positioning, and growth vision.',
        about_story_p1: 'CR Welding was created to raise the standard of welding and industrial maintenance through disciplined, technology-driven execution oriented to long-term relationships.',
        about_story_p2: 'We operate with technical authority, modernity, and reliability — attributes that are essential to keep pace with large clients and multinational operations.',
        about_story_p3: 'More than delivering services, the company structures solutions, organizes complex industrial fronts, and sustains its value proposition through continuous excellence, transparency, and commitment to lasting results.',
        about_story_p4: 'The result is a partner prepared for corporate contracts, large-scale projects, and solid presence across different geographies.',
        about_values_eyebrow: 'PRINCIPLES',
        about_values_title: 'Values that sustain the operation.',
        about_value1_title: 'Excellence',
        about_value1_desc: 'Ongoing search for technical quality, finish, and delivery predictability.',
        about_value2_title: 'Innovation',
        about_value2_desc: 'Adoption of modern approaches to expand precision, productivity, and efficiency.',
        about_value3_title: 'Safety',
        about_value3_desc: 'Operational discipline to protect teams, assets, schedules, and reputation.',
        about_value4_title: 'Trust',
        about_value4_desc: 'Transparent and lasting relationships with clients, partners, and suppliers.',
        about_model_eyebrow: 'CORPORATE MODEL',
        about_model_title: 'Prepared for larger-scale operations.',
        about_stat1_value: 'Technical execution',
        about_stat1_desc: 'Industrial scopes with operational control and focus on performance.',
        about_stat2_value: 'Institutional closeness',
        about_stat2_desc: 'Close dialogue with buyers, technical teams, and global partners.',
        about_stat3_value: 'Long-term vision',
        about_stat3_desc: 'Sustainable growth and consistent positioning in demanding markets.',
        about_manifest_title: 'Institutional manifesto',
        about_manifest_p1: 'CR Welding positions itself as a creator of solutions and governor of its own future. Its proposal is to build an industrial legacy based on technology, precision, and responsibility.',
        about_manifest_p2: 'This vision makes CR Welding a reliable partner for more complex contracts, long-term relationships, and international expansion.',
        about_gallery_eyebrow: 'OPERATIONS',
        about_gallery_title: 'CR Welding engineering in the field.',
        about_gallery_cap1: 'Specialized welding',
        about_gallery_cap2: 'Structure assembly',
      },
      services: {
        meta_title: 'CR Welding | Services',
        meta_description: 'Discover CR Welding’s industrial services, technical fronts, and execution model.',
        services_hero_eyebrow: 'SERVICES',
        services_hero_title: 'Technical portfolio structured for critical industrial demands.',
        services_hero_desc: 'CR Welding organizes its service fronts to support projects, maintenance shutdowns, capacity expansions, and recurring industrial support needs.',
        services_matrix_eyebrow: 'CAPABILITIES',
        services_matrix_title: 'Main delivery fronts.',
        services_card1_title: 'TIG Welding',
        services_card1_desc: 'Applications that require high process control, finish, and reliability.',
        services_card2_title: 'MIG/MAG Welding',
        services_card2_desc: 'Efficient execution for industrial demands with productivity and standardization.',
        services_card3_title: 'Electrode Welding',
        services_card3_desc: 'Versatility for different environments, structures, and maintenance fronts.',
        services_card4_title: 'Piping Assembly',
        services_card4_desc: 'Installation and organization of industrial systems with dimensional rigor and safety.',
        services_card5_title: 'Metal Structures',
        services_card5_desc: 'Construction, reinforcement, and structural support for production units and utilities.',
        services_card6_title: 'Skid Fabrication',
        services_card6_desc: 'Robust modular solutions for operational integration and efficiency gains.',
        services_process_eyebrow: 'EXECUTION MODEL',
        services_process_title: 'How we structure each project.',
        services_step1_title: 'Diagnosis',
        services_step1_desc: 'Technical survey, scope alignment, and priority definition.',
        services_step2_title: 'Planning',
        services_step2_desc: 'Resource organization, schedule, safety, and execution sequencing.',
        services_step3_title: 'Delivery',
        services_step3_desc: 'Execution with operational discipline, quality control, and clear communication.',
        services_step4_title: 'Continuity',
        services_step4_desc: 'Support for next phases, recurring contracts, and operation evolution.',
        services_sectors_eyebrow: 'SECTORS',
        services_sectors_title: 'Environments where CR Welding operates.',
        services_sector1_title: 'Industrial plants',
        services_sector1_desc: 'Manufacturing operations with maintenance, expansion, and reliability demands.',
        services_sector2_title: 'Utilities and infrastructure',
        services_sector2_desc: 'Production support systems that require stable performance.',
        services_sector3_title: 'Special projects',
        services_sector3_desc: 'Tailored scopes requiring technical flexibility and engineering vision.',
        services_sector4_title: 'Recurring partnerships',
        services_sector4_desc: 'Continuous relationship models with responsive operational support.',
        services_cta_title: 'Take your next industrial demand to a prepared structure.',
        services_cta_desc: 'Talk to our team to align scope, priority, and the next steps of your demand.',
        services_cta_btn_contact: 'Request contact',
        services_cta_btn_projects: 'View deliveries',
      },
      projects: {
        meta_title: 'CR Welding | Projects',
        meta_description: 'See the types of projects and representative deliveries by CR Welding for industrial operations.',
        projects_hero_eyebrow: 'PROJECTS',
        projects_hero_title: 'Representative scopes that demonstrate delivery capability.',
        projects_hero_desc: 'Get to know the types of service already executed by CR Welding and the technical capability behind every delivery.',
        projects_grid_eyebrow: 'DELIVERIES',
        projects_grid_title: 'Categories of executed projects.',
        projects_card1_title: 'Industrial piping assembly',
        projects_card1_desc: 'Execution of lines and interconnections with dimensional rigor, safety, and operational continuity.',
        projects_card2_title: 'Support metal structures',
        projects_card2_desc: 'Fabrication and assembly of structural components for production areas and utilities.',
        projects_card3_title: 'Skids and modular solutions',
        projects_card3_desc: 'Development of robust assemblies for faster integration into industrial plants.',
        projects_card4_title: 'Maintenance interventions',
        projects_card4_desc: 'Improvements, corrections, and reinforcements focused on availability and reliability.',
        projects_method_eyebrow: 'APPROACH',
        projects_method_title: 'How we conduct every delivery.',
        projects_stat1_value: 'Scope',
        projects_stat1_desc: 'Each delivery is organized by service front and expected operational result.',
        projects_stat2_value: 'Evidence',
        projects_stat2_desc: 'Field records and technical detail that prove the quality of every execution.',
        projects_stat3_value: 'Confidentiality',
        projects_stat3_desc: 'Client-identified cases are shared confidentially, subject to commercial authorization.',
        projects_media_eyebrow: 'IN THE FIELD',
        projects_media_title: 'Records that show capability and standardization.',
        projects_media_caption1: 'Technical execution and field environment.',
        projects_media_caption2: 'Consistent technical standard on every front.',
        projects_media_caption3: 'Organization and operational discipline in the field.',
        projects_cta_title: 'Get to know CR Welding’s delivery capability in detail.',
        projects_cta_desc: 'Talk to the team to learn about real cases, performance indicators, and approved references.',
        projects_cta_btn_contact: 'Request meeting',
        projects_cta_btn_faq: 'Read FAQ',
      },
      faq: {
        meta_title: 'CR Welding | FAQ',
        meta_description: 'Frequently asked questions about CR Welding’s operations, scope, timelines, and commercial relationship.',
        faq_hero_eyebrow: 'FAQ',
        faq_hero_title: 'Objective answers for faster commercial decisions.',
        faq_hero_desc: 'We gather here the most common questions about scope, capability, contracting format, and the start of a relationship with CR Welding.',
        faq_list_eyebrow: 'FREQUENTLY ASKED QUESTIONS',
        faq_list_title: 'What buyers and partners usually ask.',
        faq_q1: 'Which services does CR Welding perform?',
        faq_a1: 'The company operates with TIG, MIG/MAG, and electrode welding, piping assembly, metal structures, skid fabrication, and industrial technical support.',
        faq_q2: 'Does the company handle recurring demands or only one-off projects?',
        faq_a2: 'Both formats are possible. The operation can support one-off interventions, on-demand projects, and recurring relationships according to client needs.',
        faq_q3: 'Is CR Welding prepared for larger clients?',
        faq_a3: 'Yes. The institutional positioning, operational discipline, and organization of technical fronts were structured to engage with more demanding operations and higher-responsibility contracts.',
        faq_q4: 'How does a negotiation usually begin?',
        faq_a4: 'It usually starts with commercial contact, initial scope alignment, understanding of operational priority, and definition of the next technical steps.',
        faq_q5: 'Is there flexibility for tailored projects?',
        faq_a5: 'Yes. The company positions itself as a creator of solutions, which includes adapting fronts, resources, and delivery structure to each project context.',
        faq_q6: 'Can I see real cases and client references?',
        faq_a6: 'Yes. We share categories of scopes already executed and, subject to commercial authorization, present client-identified cases confidentially.',
        faq_q7: 'Does CR Welding serve international clients and operations?',
        faq_a7: 'Yes. We operate with a strong technical standard and bilingual communication (Portuguese and English), prepared for operations and contracts in multinational contexts.',
        faq_q8: 'What is the best next step to start a conversation?',
        faq_a8: 'Use the contact page to request an executive meeting or send an initial summary of the operational demand.',
        faq_cta_title: 'If your question is specific, move the conversation to commercial contact.',
        faq_cta_desc: 'The contact page organizes first response and helps direct the agenda more precisely.',
        faq_cta_btn_contact: 'Go to contact',
        faq_cta_btn_services: 'View services',
      },
      contact: {
        meta_title: 'CR Welding | Contact',
        meta_description: 'Contact CR Welding to present your scope, schedule a meeting, and begin a commercial relationship.',
        contact_hero_eyebrow: 'CONTACT',
        contact_hero_title: 'Open the commercial conversation with clear scope and priority.',
        contact_hero_desc: 'Here you start the first institutional contact, schedule an executive meeting, and send a summary of your operational need.',
        contact_channels_eyebrow: 'CHANNELS',
        contact_channels_title: 'Main ways to start the conversation.',
        contact_card1_title: 'Commercial email',
        contact_card1_desc: 'Ideal for sending an initial summary, preliminary scope, and supporting documents.',
        contact_card2_title: 'Executive meeting',
        contact_card2_desc: 'Recommended for larger opportunities, strategic alignment, and long-term relationships.',
        contact_card2_meta: 'Scheduling after initial contact',
        contact_card3_title: 'Demand triage',
        contact_card3_desc: 'Organizes urgency, technical front involved, and the next commercial steps.',
        contact_card3_meta: 'Response according to operational priority',
        contact_form_eyebrow: 'INITIAL FORM',
        contact_form_title: 'Send an executive brief.',
        contact_field_name: 'Name',
        contact_field_company: 'Company',
        contact_field_email: 'Email',
        contact_field_scope: 'Area of interest',
        contact_field_message: 'Need summary',
        contact_placeholder_name: 'Your name',
        contact_placeholder_company: 'Company name',
        contact_placeholder_email: 'you@company.com',
        contact_placeholder_scope: 'Ex.: piping, structure, skid',
        contact_placeholder_message: 'Describe the context, priority, and objective of the contact.',
        contact_form_button: 'Send brief',
        contact_commitment_eyebrow: 'COMMITMENTS',
        contact_commitment_title: 'Our commitment to every contact.',
        contact_commitment1_title: 'Clarity',
        contact_commitment1_desc: 'Fast reading of the demand and consistent initial direction.',
        contact_commitment2_title: 'Professionalism',
        contact_commitment2_desc: 'Professional service aligned with larger operations.',
        contact_commitment3_title: 'Continuity',
        contact_commitment3_desc: 'Opening of a commercial relationship with a medium and long-term view.',
      },
      'numbers-scale': {
        meta_title: 'CR Welding | Numbers and Scale',
        meta_description: 'CR Welding corporate structure focused on operational scale, institutional presence, and growth capacity.',
        numbers_hero_eyebrow: 'NUMBERS AND SCALE',
        numbers_hero_title: 'Size, maturity, and growth capacity to sustain your operation.',
        numbers_hero_desc: 'CR Welding is prepared to support conversations with larger clients, procurement, and strategic partners, with operational and institutional strength.',
        numbers_snapshot_eyebrow: 'OVERVIEW',
        numbers_snapshot_title: 'Core institutional indicators.',
        numbers_snapshot_desc: 'Official indicators are made available as CR Welding validates the numbers for commercial disclosure.',
        numbers_card1_title: 'Reference year',
        numbers_card1_desc: 'Foundation, current cycle, and operational milestones that frame the company’s trajectory.',
        numbers_card1_value: 'Data under consolidation',
        numbers_card2_title: 'Operational capacity',
        numbers_card2_desc: 'Team, mobilization, simultaneous fronts, or technical coverage.',
        numbers_card2_value: 'Data under consolidation',
        numbers_card3_title: 'Served markets',
        numbers_card3_desc: 'Sectors, regions, or countries according to the company’s commercial maturity.',
        numbers_card3_value: 'Data under consolidation',
        numbers_card4_title: 'Delivered projects',
        numbers_card4_desc: 'History of works, maintenance, and contracts executed throughout the operation.',
        numbers_card4_value: 'Data under consolidation',
        numbers_scale_eyebrow: 'SCALE',
        numbers_scale_title: 'Scale measured by structure, discipline, and consistency.',
        numbers_scale_p1: 'Scale is not only about revenue. It is demonstrated through structure, execution discipline, served sectors, response capacity, and operational consistency.',
        numbers_scale_p2: 'CR Welding organizes its operation to respond to more demanding contracts — and that readiness is, in itself, a commitment to trust.',
        numbers_scale_p3: 'The official indicators cover team numbers, operating areas, delivery volume, geographic presence, and capacity evolution.',
        numbers_scale_p4: 'CR Welding communicates corporate maturity with transparency, without inventing indicators or compromising brand credibility.',
        numbers_categories_eyebrow: 'CATEGORIES',
        numbers_categories_title: 'The numbers that matter most to your decision.',
        numbers_info1_title: 'Operational scale',
        numbers_info1_desc: 'Team, work fronts, mobilization capacity, and available specialties.',
        numbers_info2_title: 'Commercial scale',
        numbers_info2_desc: 'Served segments, reached markets, representative contracts, and recurrence.',
        numbers_info3_title: 'Institutional scale',
        numbers_info3_desc: 'Certifications, processes, governance, quality, and image of a prepared company.',
        numbers_cta_title: 'Operational and institutional strength, ready for larger conversations.',
        numbers_cta_desc: 'Talk to the team to receive indicators, growth milestones, and references authorized by the company.',
        numbers_cta_btn_contact: 'Move to contact',
        numbers_cta_btn_projects: 'View projects',
      },
      sectors: {
        meta_title: 'CR Welding | Served Sectors',
        meta_description: 'Learn about the industrial sectors CR Welding can serve with welding, assembly, and industrial fabrication solutions.',
        sectors_hero_eyebrow: 'SERVED SECTORS',
        sectors_hero_title: 'Where CR Welding generates value for your industrial operation.',
        sectors_hero_desc: 'We work across different industrial sectors with the same technical rigor, adapting capacity and method to the context of each operation.',
        sectors_grid_eyebrow: 'MARKETS',
        sectors_grid_title: 'Industrial sectors compatible with the company’s proposal.',
        sector1_title: 'Metalworking',
        sector1_desc: 'Structures, supports, components, and factory demands with technical and operational requirements.',
        sector2_title: 'Energy and utilities',
        sector2_desc: 'Support systems, interconnections, reinforcements, and critical fronts for operational continuity.',
        sector3_title: 'Chemical and process',
        sector3_desc: 'Environments that require disciplined assembly, reliability, and careful technical reading.',
        sector4_title: 'Food industry',
        sector4_desc: 'Structures, piping, and supports for operations that depend on standards and predictability.',
        sector5_title: 'Industrial maintenance',
        sector5_desc: 'Corrective, preventive, and improvement interventions focused on asset availability.',
        sector6_title: 'Special projects',
        sector6_desc: 'Tailor-made demands requiring technical adaptation and coordinated execution.',
        sectors_logic_eyebrow: 'SECTOR FIT',
        sectors_logic_title: 'Why sector experience makes a difference for your operation.',
        sectors_logic_p1: 'Large industrial operations do not hire just a service. They evaluate sector fit, familiarity with the operational context, and the ability to respond to specific requirements — and that is where CR Welding stands apart.',
        sectors_logic_p2: 'That is why we structure our work by sector: to respond precisely to complex operations, with no generic solutions.',
        sectors_logic_p3: 'Each sector can be detailed with cases, technical requirements, and specific certifications, according to your needs.',
        sectors_logic_p4: 'It is this approach that makes CR Welding a relevant industrial partner, not just another service provider.',
        sectors_cta_title: 'Each sector connects to CR Welding’s deliveries, indicators, and compliance.',
        sectors_cta_desc: 'Talk to the team to learn about CR Welding’s work in your sector of interest.',
        sectors_cta_btn_projects: 'View projects',
        sectors_cta_btn_compliance: 'View compliance',
      },
      compliance: {
        meta_title: 'CR Welding | Certifications and Compliance',
        meta_description: 'See how CR Welding can present certifications, quality, safety, environment, and operational governance in an institutional way.',
        compliance_hero_eyebrow: 'CERTIFICATIONS AND COMPLIANCE',
        compliance_hero_title: 'Trust that begins before the negotiation even advances.',
        compliance_hero_desc: 'Strong industrial companies do not speak only about service. They demonstrate method, system, quality, safety, and documentary reliability — and that is how CR Welding positions itself.',
        compliance_blocks_eyebrow: 'STRUCTURE',
        compliance_blocks_title: 'Pillars that sustain CR Welding’s technical credibility.',
        compliance_card1_title: 'Quality',
        compliance_card1_desc: 'Procedures, inspection, execution discipline, and continuous improvement.',
        compliance_card2_title: 'Safety',
        compliance_card2_desc: 'Prevention practices, operational conduct, and a culture of responsibility.',
        compliance_card3_title: 'Environment',
        compliance_card3_desc: 'Resource efficiency, organization, and reduction of avoidable impacts.',
        compliance_card4_title: 'Governance',
        compliance_card4_desc: 'Traceability, scope clarity, documentation, and institutional consistency.',
        compliance_matrix_eyebrow: 'TRUST MATRIX',
        compliance_matrix_title: 'The documentary foundation behind each commitment.',
        compliance_stat1_title: 'Formal certifications',
        compliance_stat1_desc: 'Seals, certification scope, validity, and document reference for each applicable standard.',
        compliance_stat1_value: 'Available upon commercial request',
        compliance_stat2_title: 'Internal procedures',
        compliance_stat2_desc: 'Quality, safety, environmental policies, and execution standards.',
        compliance_stat2_value: 'Available upon commercial request',
        compliance_stat3_title: 'Client requirements',
        compliance_stat3_desc: 'Proven adherence to each client’s contractual and operational requirements.',
        compliance_stat3_value: 'Available upon commercial request',
        compliance_stat4_title: 'Institutional evidence',
        compliance_stat4_desc: 'Clear presentation for audits, partners, and procurement areas.',
        compliance_stat4_value: 'Available upon commercial request',
        compliance_why_eyebrow: 'WHY IT MATTERS',
        compliance_why_title: 'Compliance reduces risk. And less risk means safer decisions for you.',
        compliance_why_p1: 'Documentary organization, clear processes, and transparency about quality and safety remove doubts even before the detailed technical phase.',
        compliance_why_p2: 'It is the standard of suppliers prepared to engage with larger operations and more demanding industrial chains — and that is how we work.',
        compliance_why_p3: 'Industry experience confirms it: trust is built with evidence and method, not only with commercial discourse.',
        compliance_why_p4: 'That is why we treat compliance as an essential part of every delivery — not as a formality.',
        compliance_cta_title: 'Method, procedures, and evidence that give weight to every negotiation.',
        compliance_cta_desc: 'CR Welding ensures maturity, control, and transparency at every stage of the relationship.',
        compliance_cta_btn_quality: 'View quality',
        compliance_cta_btn_contact: 'Go to contact',
      },
      'sustainability-page': {
        meta_title: 'CR Welding | Sustainability',
        meta_description: 'Learn about CR Welding’s sustainability vision and its commitments to efficiency, responsibility, and positive legacy.',
        sustain_page_hero_eyebrow: 'SUSTAINABILITY',
        sustain_page_hero_title: 'Industrial growth with responsibility, efficiency, and legacy vision.',
        sustain_page_hero_desc: 'CR Welding treats sustainability as operational discipline: less waste, better use of resources, and decisions that strengthen the future of the company, clients, and surrounding environment.',
        sustain_page_pillars_eyebrow: 'COMMITMENTS',
        sustain_page_pillars_title: 'Pillars that guide our performance.',
        sustain_page_card1_title: 'Resource efficiency',
        sustain_page_card1_desc: 'Continuous pursuit of leaner processes, less rework, and better use of materials.',
        sustain_page_card2_title: 'Operational responsibility',
        sustain_page_card2_desc: 'Organized fronts with technical discipline, safety, and control over avoidable impacts.',
        sustain_page_card3_title: 'Conscious partnerships',
        sustain_page_card3_desc: 'Relationships with clients and suppliers based on continuity, transparency, and evolving practices.',
        sustain_page_card4_title: 'Long-term vision',
        sustain_page_card4_desc: 'Growth with consistency, reputation, and positive institutional legacy.',
        sustain_page_actions_eyebrow: 'PRACTICES',
        sustain_page_actions_title: 'How this appears in practice.',
        sustain_page_step1_title: 'Planning',
        sustain_page_step1_desc: 'Scope and sequence definition focused on reducing waste and making better use of time and materials.',
        sustain_page_step2_title: 'Execution',
        sustain_page_step2_desc: 'Quality-oriented technical standard to minimize rework and unnecessary corrective interventions.',
        sustain_page_step3_title: 'Discipline',
        sustain_page_step3_desc: 'Safety, organized environment, and operational conduct compatible with larger operations.',
        sustain_page_step4_title: 'Evolution',
        sustain_page_step4_desc: 'Continuous learning to elevate performance, efficiency, and company maturity.',
      },
      quality: {
        meta_title: 'CR Welding | Quality',
        meta_description: 'Learn about CR Welding’s quality vision, execution principles, and continuous improvement approach.',
        quality_hero_eyebrow: 'QUALITY',
        quality_hero_title: 'Quality as execution discipline, reputation, and permanence.',
        quality_hero_desc: 'At CR Welding, quality is not isolated finishing. It is method, control, predictability, and commitment to results that sustain commercial trust.',
        quality_principles_eyebrow: 'PRINCIPLES',
        quality_principles_title: 'Elements that form our internal standard.',
        quality_card1_title: 'Standardization',
        quality_card1_desc: 'Consistent processes to reduce variation and increase the reliability of every delivery.',
        quality_card2_title: 'Control',
        quality_card2_desc: 'Technical monitoring and clear scope reading throughout execution.',
        quality_card3_title: 'Traceability',
        quality_card3_desc: 'Organization of stages and decisions to facilitate communication and operational evolution.',
        quality_card4_title: 'Continuous improvement',
        quality_card4_desc: 'Learning embedded in the method to increase performance and predictability.',
        quality_model_eyebrow: 'MODEL',
        quality_model_title: 'How quality appears in service fronts.',
        quality_model_p1: 'In welding, quality means process control, coherence in execution, and reduction of rework.',
        quality_model_p2: 'In assembly and fabrication, it means precision, correct scope reading, and alignment between technical delivery and client need.',
        quality_model_p3: 'In commercial relationships, quality also means clarity, communication consistency, and commitment to what was agreed.',
        quality_model_p4: 'This set strengthens reputation, contractual continuity, and the ability to operate in more demanding environments.',
      },
      careers: {
        meta_title: 'CR Welding | Careers',
        meta_description: 'Learn about CR Welding careers, work culture, and the professional profiles sought by the company.',
        careers_hero_eyebrow: 'CAREERS',
        careers_hero_title: 'People who build standards, trust, and operational continuity.',
        careers_hero_desc: 'We look for professionals aligned with industrial discipline, technical standards, and the ambition to grow together with CR Welding.',
        careers_culture_eyebrow: 'CULTURE',
        careers_culture_title: 'What we value in teams.',
        careers_card1_title: 'Discipline',
        careers_card1_desc: 'Commitment to technical standards, safety, and organization at work.',
        careers_card2_title: 'Learning',
        careers_card2_desc: 'Continuous evolution as part of individual and collective growth.',
        careers_card3_title: 'Responsibility',
        careers_card3_desc: 'Professional posture compatible with more demanding operations and clients.',
        careers_card4_title: 'Partnership',
        careers_card4_desc: 'Ability to collaborate, respect processes, and strengthen the team.',
        careers_profiles_eyebrow: 'PROFILES',
        careers_profiles_title: 'Profiles that make a difference in our teams.',
        careers_profile1_title: 'Specialized welders',
        careers_profile1_desc: 'Professionals focused on quality, method, and technical consistency.',
        careers_profile2_title: 'Assemblers and field support',
        careers_profile2_desc: 'Operational profiles oriented to safe and organized execution.',
        careers_profile3_title: 'Technical coordination',
        careers_profile3_desc: 'Leadership with vision for process, people, delivery, and client relationship.',
        careers_cta_title: 'Be part of CR Welding’s industrial growth.',
        careers_cta_desc: 'Send your introduction and show how you align with CR Welding’s culture, ambition, and professional standard.',
        careers_cta_btn_email: 'Send introduction',
        careers_cta_btn_about: 'Learn about the company',
      },
    },
  },
};

function getDictionary(lang, page) {
  const locale = translations[lang] || translations.pt;
  return {
    ...locale.common,
    ...(locale.pages[page] || {}),
  };
}

function applyLanguage(lang) {
  const selected = translations[lang] ? lang : 'pt';
  const page = document.body.dataset.page || 'home';
  const dict = getDictionary(selected, page);

  document.documentElement.lang = selected === 'pt' ? 'pt-BR' : 'en';

  const titleEl = document.getElementById('page-title');
  if (titleEl && dict.meta_title) {
    titleEl.textContent = dict.meta_title;
    document.title = dict.meta_title;
  }

  const metaDescription = document.getElementById('meta-description');
  if (metaDescription && dict.meta_description) {
    metaDescription.setAttribute('content', dict.meta_description);
  }

  document.querySelectorAll('[data-i18n]').forEach((node) => {
    const key = node.getAttribute('data-i18n');
    if (key && dict[key]) {
      node.textContent = dict[key];
    }
  });

  document.querySelectorAll('[data-i18n-alt]').forEach((node) => {
    const key = node.getAttribute('data-i18n-alt');
    if (key && dict[key]) {
      node.setAttribute('alt', dict[key]);
    }
  });

  document.querySelectorAll('[data-i18n-aria-label]').forEach((node) => {
    const key = node.getAttribute('data-i18n-aria-label');
    if (key && dict[key]) {
      node.setAttribute('aria-label', dict[key]);
    }
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach((node) => {
    const key = node.getAttribute('data-i18n-placeholder');
    if (key && dict[key]) {
      node.setAttribute('placeholder', dict[key]);
    }
  });

  document.querySelectorAll('.lang-btn').forEach((button) => {
    const isActive = button.dataset.lang === selected;
    button.classList.toggle('active', isActive);
    button.setAttribute('aria-pressed', String(isActive));
  });

  localStorage.setItem('crw_language', selected);
}

document.querySelectorAll('.lang-btn').forEach((button) => {
  button.addEventListener('click', () => {
    applyLanguage(button.dataset.lang || 'pt');
  });
});

const browserLang = (navigator.language || '').toLowerCase();
const persistedLang = localStorage.getItem('crw_language');
const initialLang = persistedLang || (browserLang.startsWith('en') ? 'en' : 'pt');
applyLanguage(initialLang);

/* ============================================================
   CAMADA VISUAL PREMIUM — interações
   ============================================================ */
(function () {
  const prefersReduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  /* --- Parallax suave nos heros (move a posição da imagem de fundo) --- */
  const heroLayers = document.querySelectorAll('.section-hero, .subpage-hero');
  if (heroLayers.length && !prefersReduced) {
    let ticking = false;
    const update = () => {
      const shift = Math.min(window.scrollY * 0.16, 110);
      heroLayers.forEach((el) => el.style.setProperty('--hero-shift', shift + 'px'));
      ticking = false;
    };
    window.addEventListener(
      'scroll',
      () => {
        if (!ticking) {
          requestAnimationFrame(update);
          ticking = true;
        }
      },
      { passive: true }
    );
    update();
  }

  /* --- Lightbox para o portfólio (clique para ampliar) --- */
  const triggers = document.querySelectorAll('[data-lightbox]');
  if (triggers.length) {
    const lb = document.createElement('div');
    lb.className = 'lightbox';
    lb.setAttribute('role', 'dialog');
    lb.setAttribute('aria-modal', 'true');
    lb.innerHTML =
      '<button class="lightbox-close" type="button" aria-label="Fechar">×</button><img alt="" />';
    document.body.appendChild(lb);
    const lbImg = lb.querySelector('img');
    const closeLb = () => {
      lb.classList.remove('open');
      document.body.style.overflow = '';
    };
    triggers.forEach((fig) => {
      fig.addEventListener('click', () => {
        const img = fig.querySelector('img');
        if (!img) return;
        lbImg.src = img.currentSrc || img.src;
        lbImg.alt = img.alt || '';
        lb.classList.add('open');
        document.body.style.overflow = 'hidden';
      });
    });
    lb.addEventListener('click', (event) => {
      if (event.target !== lbImg) closeLb();
    });
    document.addEventListener('keydown', (event) => {
      if (event.key === 'Escape' && lb.classList.contains('open')) closeLb();
    });
  }
})();
